version: '3'
services:
  arenas:
    image: rwbyadventures:latest
    network_mode: host
    entrypoint: /app/arenas
  dungeons:
    image: rwbyadventures:latest
    network_mode: host
    entrypoint: /app/dungeons
  market_back:
    image: rwbyadventures:latest
    network_mode: host
    entrypoint: /app/market
  market_frontend:
    image: rwbyadventures:latest
    network_mode: host
    entrypoint: http-server /app/market_front/dist
  main:
    image: rwbyadventures:latest
    network_mode: host
    entrypoint: /app/main
