version: '3.5'

services:
  docker-registry:
    image: registry:2
    container_name: rwby_registry
    restart: always
    environment:
      - VIRTUAL_HOST=registry.wordchamp.info
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=registry.wordchamp.info
      - LETSENCRYPT_EMAIL=admin@wordchamp.info
    volumes:
      - ./registry:/var/lib/registry
    networks:
      - docker-network
  rwby_database:
    container_name: rwby_db
    image: postgres:14.5-alpine
    restart: always
    env_file:
      - prod.env
    #ports:
    #  - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - docker-network
  arenas:
    image: registry.wordchamp.info/rwbyadventures:latest
    entrypoint: /app/arenas
    env_file:
      - prod.env
    environment:
      - VIRTUAL_HOST=arena.beta.rwbyadventures.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=arena.beta.rwbyadventures.com
      - LETSENCRYPT_EMAIL=admin@beta.rwbyadventures.com
    restart: always
    depends_on:
      - rwby_database
      - docker-registry
    networks:
      - docker-network
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    cap_add:
      - net_bind_service
  arenas-ws:
    image: marcnuri/port-forward
    env_file:
      - prod.env
    environment:
      - VIRTUAL_HOST=ws.arena.rwbyadventures.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=ws.arena.rwbyadventures.com
      - LETSENCRYPT_EMAIL=admin@beta.rwbyadventures.com
      - REMOTE_HOST=arenas
      - REMOTE_PORT=9001
    restart: always
    depends_on:
      - rwby_database
      - docker-registry
    networks:
      - docker-network
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    cap_add:
      - net_bind_service
  dungeons:
    image: registry.wordchamp.info/rwbyadventures:latest
    entrypoint: /app/dungeons
    restart: always
    env_file:
      - prod.env
    environment:
      - VIRTUAL_HOST=dungeon.beta.rwbyadventures.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=dungeon.beta.rwbyadventures.com
      - LETSENCRYPT_EMAIL=admin@beta.rwbyadventures.com
    depends_on:
      - rwby_database
      - docker-registry
    networks:
      - docker-network
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    cap_add:
      - net_bind_service
  dungeons-ws:
    image: marcnuri/port-forward
    env_file:
      - prod.env
    environment:
      - VIRTUAL_HOST=ws.dungeon.rwbyadventures.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=ws.dungeon.rwbyadventures.com
      - LETSENCRYPT_EMAIL=admin@beta.rwbyadventures.com
      - REMOTE_HOST=dungeons
      - REMOTE_PORT=9002
    restart: always
    depends_on:
      - rwby_database
      - docker-registry
    networks:
      - docker-network
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    cap_add:
      - net_bind_service
  market_back:
    image: registry.wordchamp.info/rwbyadventures:latest
    entrypoint: /app/market
    restart: always
    env_file:
      - prod.env
    environment:
      - VIRTUAL_HOST=api.market.beta.rwbyadventures.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=api.market.beta.rwbyadventures.com
      - LETSENCRYPT_EMAIL=admin@beta.rwbyadventures.com
    depends_on:
      - rwby_database
      - docker-registry
    networks:
      - docker-network
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    cap_add:
      - net_bind_service
  market-ws:
    image: marcnuri/port-forward
    env_file:
      - prod.env
    environment:
      - VIRTUAL_HOST=ws.market.rwbyadventures.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=ws.market.rwbyadventures.com
      - LETSENCRYPT_EMAIL=admin@beta.rwbyadventures.com
      - REMOTE_HOST=market_back
      - REMOTE_PORT=9003
    restart: always
    depends_on:
      - rwby_database
      - docker-registry
    networks:
      - docker-network
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    cap_add:
      - net_bind_service
  market_frontend:
    image: registry.wordchamp.info/rwbyadventures:latest
    entrypoint: http-server /app/market_front/dist
    restart: always
    env_file:
      - prod.env
    environment:
      - VIRTUAL_HOST=market.beta.rwbyadventures.com
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=market.beta.rwbyadventures.com
      - LETSENCRYPT_EMAIL=admin@beta.rwbyadventures.com
    depends_on:
      - rwby_database
      - docker-registry
    networks:
      - docker-network
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    cap_add:
      - net_bind_service
  topgg:
    image: registry.wordchamp.info/rwbyadventures:latest
    entrypoint: /app/topgg
    restart: always
    env_file:
      - prod.env
    environment:
      - VIRTUAL_HOST=topgg.beta.rwbyadventures.com
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=topgg.beta.rwbyadventures.com
      - LETSENCRYPT_EMAIL=admin@beta.rwbyadventures.com
    depends_on:
      - rwby_database
      - docker-registry
    networks:
      - docker-network
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    cap_add:
      - net_bind_service
  gambles:
    image: registry.wordchamp.info/rwbyadventures:latest
    entrypoint: /app/gambles
    restart: always
    env_file:
      - prod.env
    environment:
      - VIRTUAL_HOST=gambles.beta.rwbyadventures.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=gambles.beta.rwbyadventures.com
      - LETSENCRYPT_EMAIL=admin@beta.rwbyadventures.com
    depends_on:
      - rwby_database
      - docker-registry
    networks:
      - docker-network
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    cap_add:
      - net_bind_service
  main:
    image: registry.wordchamp.info/rwbyadventures:latest
    entrypoint: /app/main
    restart: always
    env_file:
      - prod.env
    environment:
      - VIRTUAL_HOST=trade.beta.rwbyadventures.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=trade.beta.rwbyadventures.com
      - LETSENCRYPT_EMAIL=admin@beta.rwbyadventures.com
    depends_on:
      - rwby_database
      - docker-registry
    networks:
      - docker-network
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    cap_add:
      - net_bind_service
  main-ws:
    image: marcnuri/port-forward
    env_file:
      - prod.env
    environment:
      - VIRTUAL_HOST=ws.trade.rwbyadventures.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=ws.trade.rwbyadventures.com
      - LETSENCRYPT_EMAIL=admin@beta.rwbyadventures.com
      - REMOTE_HOST=main
      - REMOTE_PORT=9000
    restart: always
    depends_on:
      - rwby_database
      - docker-registry
    networks:
      - docker-network
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    cap_add:
      - net_bind_service

networks:
  docker-network:
    driver: bridge
    name: docker-network