// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.2
// source: arenas.proto

package arenapc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ping string `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
}

func (x *PingReq) Reset() {
	*x = PingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_arenas_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReq) ProtoMessage() {}

func (x *PingReq) ProtoReflect() protoreflect.Message {
	mi := &file_arenas_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReq.ProtoReflect.Descriptor instead.
func (*PingReq) Descriptor() ([]byte, []int) {
	return file_arenas_proto_rawDescGZIP(), []int{0}
}

func (x *PingReq) GetPing() string {
	if x != nil {
		return x.Ping
	}
	return ""
}

type PingRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pong string `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
}

func (x *PingRep) Reset() {
	*x = PingRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_arenas_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRep) ProtoMessage() {}

func (x *PingRep) ProtoReflect() protoreflect.Message {
	mi := &file_arenas_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRep.ProtoReflect.Descriptor instead.
func (*PingRep) Descriptor() ([]byte, []int) {
	return file_arenas_proto_rawDescGZIP(), []int{1}
}

func (x *PingRep) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

type CreateArenaReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateArenaReq) Reset() {
	*x = CreateArenaReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_arenas_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateArenaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArenaReq) ProtoMessage() {}

func (x *CreateArenaReq) ProtoReflect() protoreflect.Message {
	mi := &file_arenas_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArenaReq.ProtoReflect.Descriptor instead.
func (*CreateArenaReq) Descriptor() ([]byte, []int) {
	return file_arenas_proto_rawDescGZIP(), []int{2}
}

func (x *CreateArenaReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateArenaRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Loots  string `protobuf:"bytes,2,opt,name=loots,proto3" json:"loots,omitempty"`
}

func (x *CreateArenaRep) Reset() {
	*x = CreateArenaRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_arenas_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateArenaRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArenaRep) ProtoMessage() {}

func (x *CreateArenaRep) ProtoReflect() protoreflect.Message {
	mi := &file_arenas_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArenaRep.ProtoReflect.Descriptor instead.
func (*CreateArenaRep) Descriptor() ([]byte, []int) {
	return file_arenas_proto_rawDescGZIP(), []int{3}
}

func (x *CreateArenaRep) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateArenaRep) GetLoots() string {
	if x != nil {
		return x.Loots
	}
	return ""
}

var File_arenas_proto protoreflect.FileDescriptor

var file_arenas_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x61, 0x72, 0x65, 0x6e, 0x61, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07,
	0x61, 0x72, 0x65, 0x6e, 0x61, 0x70, 0x63, 0x22, 0x1d, 0x0a, 0x07, 0x50, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x22, 0x1d, 0x0a, 0x07, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x70, 0x6f, 0x6e, 0x67, 0x22, 0x20, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41,
	0x72, 0x65, 0x6e, 0x61, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3e, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x41, 0x72, 0x65, 0x6e, 0x61, 0x52, 0x65, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x6f, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6c, 0x6f, 0x6f, 0x74, 0x73, 0x32, 0x78, 0x0a, 0x05, 0x41, 0x72, 0x65, 0x6e, 0x61,
	0x12, 0x41, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x65, 0x6e, 0x61, 0x12,
	0x17, 0x2e, 0x61, 0x72, 0x65, 0x6e, 0x61, 0x70, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x41, 0x72, 0x65, 0x6e, 0x61, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x61, 0x72, 0x65, 0x6e, 0x61,
	0x70, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x65, 0x6e, 0x61, 0x52, 0x65,
	0x70, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x10, 0x2e, 0x61, 0x72,
	0x65, 0x6e, 0x61, 0x70, 0x63, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e,
	0x61, 0x72, 0x65, 0x6e, 0x61, 0x70, 0x63, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x22,
	0x00, 0x42, 0x31, 0x0a, 0x17, 0x72, 0x77, 0x62, 0x79, 0x2e, 0x61, 0x64, 0x76, 0x65, 0x6e, 0x74,
	0x75, 0x72, 0x65, 0x73, 0x2e, 0x61, 0x72, 0x65, 0x6e, 0x61, 0x70, 0x63, 0x42, 0x0a, 0x41, 0x72,
	0x65, 0x6e, 0x61, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x08, 0x2f, 0x61, 0x72, 0x65,
	0x6e, 0x61, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_arenas_proto_rawDescOnce sync.Once
	file_arenas_proto_rawDescData = file_arenas_proto_rawDesc
)

func file_arenas_proto_rawDescGZIP() []byte {
	file_arenas_proto_rawDescOnce.Do(func() {
		file_arenas_proto_rawDescData = protoimpl.X.CompressGZIP(file_arenas_proto_rawDescData)
	})
	return file_arenas_proto_rawDescData
}

var file_arenas_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_arenas_proto_goTypes = []interface{}{
	(*PingReq)(nil),        // 0: arenapc.PingReq
	(*PingRep)(nil),        // 1: arenapc.PingRep
	(*CreateArenaReq)(nil), // 2: arenapc.CreateArenaReq
	(*CreateArenaRep)(nil), // 3: arenapc.CreateArenaRep
}
var file_arenas_proto_depIdxs = []int32{
	2, // 0: arenapc.Arena.CreateArena:input_type -> arenapc.CreateArenaReq
	0, // 1: arenapc.Arena.Ping:input_type -> arenapc.PingReq
	3, // 2: arenapc.Arena.CreateArena:output_type -> arenapc.CreateArenaRep
	1, // 3: arenapc.Arena.Ping:output_type -> arenapc.PingRep
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_arenas_proto_init() }
func file_arenas_proto_init() {
	if File_arenas_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_arenas_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_arenas_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_arenas_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateArenaReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_arenas_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateArenaRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_arenas_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_arenas_proto_goTypes,
		DependencyIndexes: file_arenas_proto_depIdxs,
		MessageInfos:      file_arenas_proto_msgTypes,
	}.Build()
	File_arenas_proto = out.File
	file_arenas_proto_rawDesc = nil
	file_arenas_proto_goTypes = nil
	file_arenas_proto_depIdxs = nil
}
